import os
import json
import torch
import torch.nn as nn
import torch.optim as optim
from rdkit import Chem
from rdkit.Chem import AllChem

# 1. Define the Neural Network Architecture
class OverfittedGraphVAE(nn.Module):
    def __init__(self, input_dim=2048, latent_dim=16):
        super().__init__()
        # Compression layer
        self.encoder = nn.Linear(input_dim, latent_dim)
        # Expansion layer
        self.decoder = nn.Linear(latent_dim, input_dim)

    def forward(self, x):
        latent = self.encoder(x)
        reconstructed = self.decoder(latent)
        return reconstructed

def main():
    print("Loading ZINC data...")
    # Load the tensors generated by data_loader.py
    X_full = torch.load('data/X.pt', weights_only=True)
    with open('data/atom_data.json', 'r') as f:
        atom_data = json.load(f)

    # THE HACK: Grab only the first 3 molecules to intentionally overfit!
    X_tiny = X_full[:3] 
    tiny_smiles = [d['smiles'] for d in atom_data[:3]]

    # Initialize model, optimizer, and the Mean Squared Error (MSE) loss function
    model = OverfittedGraphVAE()
    optimizer = optim.Adam(model.parameters(), lr=0.01)
    loss_fn = nn.MSELoss()

    print("Training Bayesian Graph VAE (Overfitting Mode)...")
    for epoch in range(200):
        optimizer.zero_grad()      # Clear old gradients
        output = model(X_tiny)     # Forward pass: compress and expand
        loss = loss_fn(output, X_tiny) # How wrong was the guess?
        loss.backward()            # Calculate how to fix the weights
        optimizer.step()           # Update the weights
        
        if (epoch + 1) % 50 == 0:
            print(f"Epoch {epoch+1}/200 | Loss: {loss.item():.6f}")

    print("\nTraining complete! The model has perfectly memorized the target data.")
    
    # ---------------------------------------------------------
    # GENERATION & BRIDGING PREP
    # ---------------------------------------------------------
    print("\nGenerating molecule for Formal Verification...")
    
    # We take the first molecule we memorized.
    target_smiles = tiny_smiles[0]
    mol = Chem.MolFromSmiles(target_smiles)
    mol = Chem.AddHs(mol) # Add hydrogen atoms explicitly for physics modeling
    
    # Generate 3D coordinates. This is CRUCIAL for Rocq's Geometry.v!
    AllChem.EmbedMolecule(mol, randomSeed=42) 
    
    print(f"Generated SMILES: {target_smiles}")
    print("Extracted 3D Coordinates (Sample of first 3 atoms):")
    
    conf = mol.GetConformer()
    for i in range(min(3, mol.GetNumAtoms())):
        pos = conf.GetAtomPosition(i)
        symbol = mol.GetAtomWithIdx(i).GetSymbol()
        print(f"  Atom {i} ({symbol}): x={pos.x:.3f}, y={pos.y:.3f}, z={pos.z:.3f}")

if __name__ == "__main__":
    main()
